# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

# Site
locale: "en"
title: Noest docs
title_seperator : "-"
subtitle: Code conventions, best practices and configuration files.
name: Noest
description: This is the document site of Noest.
url: "https://noest.it"
baseurl: /
repository: "https://github.com/noestit/Noestit.github.io/"
logo: 'assets/images/Block_Logo_Green.png'
words_per_minute: 200
search: false

# Site Footer
footer:
   links:
      - label: "Email"
        icon: "fas fa-fw fa-envelope-square"
        url: "mailto:info@noest.it"
      - label: "Website"
        icon: "fas fa-fw fa-link"
        url: "https://noest.it"
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/teamnoest"
      - label: "Facebook"
        icon: "fab fa-fw fa-facebook-square"
        url: "https://www.facebook.com/teamnoest"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/noestit"
      - label: "Linkedin"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/company/teamnoest/mycompany"
      - label: "Instagram"
        icon: "fab fa-fw fa-instagram"
        url: "https://www.instagram.com/teamnoest"

# Reading Files
include:
   [
      "_pages",
      "assets",
      .editorconfig,
   ]

exclude:
  [
    changelog.md, 
    LICENSE.txt, 
    README.md, 
    CONDUCT.MD, 
    CONTRIBUTING.md,
    Gemfile, 
    Gemfile.lock,
  ]

permalink: /:title/
email: info@noest.it


plugins:
   - jekyll-include-cache
